hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    timeout_min: 60
    cpus_per_task: 4
    gpus_per_node: null
    tasks_per_node: 1
    mem_gb: 16
    nodes: 1
    name: ${hydra.job.name}
    stderr_to_stdout: false
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    partition: null
    qos: null
    comment: null
    constraint: null
    exclude: null
    gres: null
    cpus_per_gpu: null
    gpus_per_task: null
    mem_per_gpu: null
    mem_per_cpu: null
    account: null
    signal_delay_s: 120
    max_num_timeout: 0
    additional_parameters:
      time: 1-00:00:00
    array_parallelism: 16
    setup: null
    _convert_: object
    job_name: submitit
    time: 5
    ntasks_per_node: null
    num_gpus: null
    mem: null
    mail_type: null
    mail_user: null
    nodelist: null
    dependency: null
    exclusive: null
    wckey: submitit
    srun_args: null
    use_srun: true
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra: []
    task: []
  job:
    name: main
    chdir: null
    override_dirname: ''
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /home/adam/Documents/MILA/projects/ood-slam
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: ood_slam.configs
      schema: pkg
      provider: main
    - path: hydra_plugins.hydra_colorlog.conf
      schema: pkg
      provider: hydra-colorlog
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      cluster: null
      experiment: null
      resources: cpu
      data: deepvo_kitti
      model: deepvo
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: patched_submitit_slurm
      hydra/output: default
  verbose: false
experiment_name: ood_slam_deepvo
seed: 42
learning_rate: 0.001
batch_size: 32
max_epochs: 10
scratch_dir: ${get_constant:SCRATCH}
slurm_tmpdir: ${get_constant:SLURM_TMPDIR}
use_wandb: true
wandb:
  project: ood-slam
  name: ${experiment_name}_${now:%Y%m%d_%H%M%S}
debug: false
model:
  rnn_hidden_size: 1000
  conv_dropout:
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.5
  rnn_dropout_out: 0.5
  rnn_dropout_between: 0
  batch_norm: true
  pretrained_flownet: null
data:
  _target_: data.image_seq_datamodule.ImageSequenceDataModule
  data_dir: ${get_constant:DATA_DIR}/KITTI
  train_sequences:
  - '00'
  - '01'
  - '02'
  - '05'
  - '08'
  - '09'
  valid_sequences:
  - '04'
  - '06'
  - '07'
  - '10'
  img_w: 608
  img_h: 184
  img_means:
  - 0.19007764876619865
  - 0.15170388157131237
  - 0.10659445665650864
  img_stds:
  - 0.2610784009469139
  - 0.25729316928935814
  - 0.25163823815039915
  resize_mode: rescale
  minus_point_5: true
  seq_len:
  - 5
  - 7
  sample_times: 3
  batch_size: ${batch_size}
  num_workers: 4
  pin_memory: true
  use_cache: true
  cache_dir: null
trainer:
  accelerator: cpu
  devices: auto
